#!/usr/bin/env python3
"""
Test script for Hormozi scraper.

Usage:
    python test_hormozi_scraper.py --mode quick    # 5 videos, 20 tweets
    python test_hormozi_scraper.py --mode full     # 50 videos, 1000 tweets
"""

import asyncio
import json
import sys
from datetime import datetime
from pathlib import Path

from backend.scrapers.adapters.hormozi import HormoziScraper


async def test_health_check():
    """Test scraper health check."""
    print("🏥 Running health check...")
    scraper = HormoziScraper()
    health = await scraper.health_check()
    print(json.dumps(health, indent=2))
    return health["status"] == "ok"


async def test_quick_scrape():
    """Quick test: 5 videos + 20 tweets."""
    print("\n🚀 Running QUICK scrape (5 videos, 20 tweets)...\n")
    scraper = HormoziScraper()

    report = await scraper.scrape_all(
        youtube_limit=5,
        twitter_limit=20
    )

    return report


async def test_full_scrape():
    """Full scrape: 50 videos + 1000 tweets."""
    print("\n🚀 Running FULL scrape (50 videos, 1000 tweets)...\n")
    scraper = HormoziScraper()

    report = await scraper.scrape_all(
        youtube_limit=50,
        twitter_limit=1000
    )

    return report


def save_report(report: dict, mode: str):
    """Save report to JSON and generate markdown summary."""
    # Create output directory
    output_dir = Path("hormozi_scraper_output")
    output_dir.mkdir(exist_ok=True)

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

    # Save full JSON report
    json_path = output_dir / f"hormozi_report_{mode}_{timestamp}.json"

    # Convert UnifiedContent objects to dicts for JSON serialization
    report_copy = report.copy()
    report_copy["content"] = [
        content.model_dump() for content in report["content"]
    ]

    with open(json_path, "w") as f:
        json.dump(report_copy, f, indent=2, default=str)

    print(f"\n💾 Full report saved to: {json_path}")

    # Generate markdown summary
    md_path = output_dir / f"hormozi_summary_{mode}_{timestamp}.md"

    with open(md_path, "w") as f:
        f.write("# Alex Hormozi Content Scraper Report\n\n")
        f.write(f"**Generated**: {report['timestamp']}\n")
        f.write(f"**Mode**: {mode.upper()}\n\n")

        f.write("## 📊 Summary\n\n")
        f.write(f"- **YouTube Videos**: {report['summary']['videos_scraped']}\n")
        f.write(f"- **Twitter Posts**: {report['summary']['tweets_scraped']}\n")
        f.write(f"- **Total Items**: {report['summary']['total_items']}\n")
        f.write(f"- **Credits Used**: {report['summary']['credits_used']}\n")
        f.write(f"- **Credits Remaining**: {report['summary']['credits_remaining']}\n\n")

        f.write("## 💡 Marketing Insights\n\n")
        f.write(f"- **Frameworks Identified**: {report['insights']['framework_count']}\n")
        f.write(f"- **Themes Detected**: {report['insights']['theme_count']}\n")
        f.write(f"- **Hook Patterns**: {len(report['insights']['hooks_identified'])}\n\n")

        if report['insights']['frameworks_identified']:
            f.write("### 🎯 Frameworks Detected\n\n")
            for framework in report['insights']['frameworks_identified']:
                f.write(f"- {framework}\n")
            f.write("\n")

        if report['insights']['themes_identified']:
            f.write("### 📚 Themes Identified\n\n")
            for theme in report['insights']['themes_identified']:
                f.write(f"- {theme}\n")
            f.write("\n")

        if report['insights']['hooks_identified']:
            f.write("### 🎣 Hook Patterns\n\n")
            for hook in report['insights']['hooks_identified']:
                f.write(f"- {hook}\n")
            f.write("\n")

        f.write("## 📈 Platform Breakdown\n\n")
        f.write("### YouTube\n\n")
        yt = report['platform_breakdown']['youtube']
        f.write(f"- Videos: {yt['count']}\n")
        f.write(f"- Total Views: {yt['total_views']:,}\n")
        f.write(f"- Total Likes: {yt['total_likes']:,}\n\n")

        f.write("### Twitter\n\n")
        tw = report['platform_breakdown']['twitter']
        f.write(f"- Tweets: {tw['count']}\n")
        f.write(f"- Total Likes: {tw['total_likes']:,}\n")
        f.write(f"- Total Retweets: {tw['total_retweets']:,}\n\n")

        f.write("---\n\n")
        f.write(f"*Generated by Hormozi Scraper Agent #4*\n")

    print(f"📝 Summary saved to: {md_path}")

    return json_path, md_path


async def main():
    """Main test runner."""
    mode = "quick"

    # Parse command line args
    if len(sys.argv) > 1:
        if "--mode" in sys.argv:
            idx = sys.argv.index("--mode")
            if idx + 1 < len(sys.argv):
                mode = sys.argv[idx + 1]

    print("="*60)
    print("🎯 HORMOZI CONTENT SCRAPER TEST")
    print("="*60)
    print(f"Mode: {mode.upper()}\n")

    # Health check
    if not await test_health_check():
        print("❌ Health check failed!")
        return 1

    # Run scrape
    if mode == "quick":
        report = await test_quick_scrape()
    elif mode == "full":
        report = await test_full_scrape()
    else:
        print(f"❌ Unknown mode: {mode}")
        print("   Use: --mode quick or --mode full")
        return 1

    # Save results
    json_path, md_path = save_report(report, mode)

    print("\n✅ Test complete!")
    return 0


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
